### PR TITLE
Add white background to icons

### PR DESCRIPTION
**Pull request by daaru00**

### CODE REVIEW

**Comment by lorenaramonda** [comment]
uhmmm there's something broken on mac, the icon disappeared 😕 
Schermata 2019-08-15 alle 19 34 22

**Comment by lorenaramonda** [comment]
but the tray icon changed 
Schermata 2019-08-15 alle 19 37 00

**Comment by daaru00** [comment]
Now? (I regenerated the icon) always the same issue?

**Review by lorenaramonda — APPROVED** [review]
ok now i'ts ok although this icon is not the best one I ever seen but this will be another task eventually 😛

**Pull request merged**
